// src/components/Navbar.vue
<script setup>
import { ref } from 'vue'

const navOpen = ref(false)

</script>

<template>
  <div>
    <!-- Mobile Navigation Section -->
    <div class="sm:hidden px-4 py-2 bg-purple-500">
      <div class="flex items-center justify-between">
        <!-- Burger/Close Button -->
        <button @click="navOpen = !navOpen" class="text-white">
          <!-- Burger icon -->
          <svg v-show="!navOpen" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 9h16.5m-16.5 6.75h16.5" />
          </svg>
          <!-- Close icon -->
          <svg v-show="navOpen" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="m9.75 9.75 4.5 4.5m0-4.5-4.5 4.5M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
        </button>
        <!-- Mobile Logo -->
        <router-link to="/" class="font-bold text-white text-xl">
          LanceSports
        </router-link>
      </div>

      <!-- Mobile Menu (toggled by navOpen) -->
      <nav v-show="navOpen" class="text-white mt-4 space-y-2">
        <!-- These are now <router-link> components -->
        <router-link to="/premier-league" class="block">Premier League</router-link>
        <router-link to="/psl" class="block">PSL</router-link>
        <router-link to="/rugby" class="block">Rugby</router-link>
        <router-link to="/cricket" class="block">Cricket</router-link>
        <!-- Login button is also a router link -->
        <router-link to="/login" class="block bg-white text-purple-500 px-4 py-2 rounded font-semibold text-center hover:bg-purple-100 transition">
          Login
        </router-link>
      </nav>
    </div>

    <!-- Desktop Navigation Section -->
    <div class="px-4 py-2 bg-purple-500 hidden sm:block">
      <div class="flex gap-x-10 text-white items-center">
        <!-- Desktop Logo -->
        <router-link to="/" class="font-bold text-white text-xl">
          LanceSports
        </router-link>
        <!-- These are now <router-link> components -->
        <router-link to="/premier-league" class="block">Premier League</router-link>
        <router-link to="/psl" class="block">PSL</router-link>
        <router-link to="/rugby" class="block">Rugby</router-link>
        <router-link to="/cricket" class="block">Cricket</router-link>
        <!-- Login button as a router link -->
        <router-link to="/login" class="ml-auto bg-white text-purple-500 px-4 py-2 rounded font-semibold hover:bg-purple-100 transition">
          Login
        </router-link>
      </div>
    </div>
  </div>
</template>

<style scoped>
/*
  The router-link-active class is automatically added to the active link.
  You can use it to apply styles like a bold font or a different color
  to indicate the current page.
*/
.router-link-active {
  font-weight: bold;
}
</style>

// Lance-Sports/src/components/Navbar.tsx
import { useState } from 'react';
import { Button } from './ui/button';
import { Menu, X } from 'lucide-react';

interface NavbarProps {
  onLoginClick?: () => void;
  isSignedIn?: boolean;
  onLogout?: () => void;
}

export function Navbar({ onLoginClick, isSignedIn = false, onLogout }: NavbarProps) {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  const navItems = [
    { name: 'Premier League', href: '#premier-league' },
    { name: 'PSL', href: '#psl' },
    { name: 'Rugby', href: '#rugby' },
    { name: 'Cricket', href: '#cricket' }
  ];

  return (
    <nav className="bg-green-600 text-white px-4 py-3">
      <div className="max-w-7xl mx-auto flex items-center justify-between">
        {/* Logo */}
        <div className="text-xl font-semibold">
          LanceSports
        </div>

        {/* Desktop Navigation */}
        <div className="hidden md:flex items-center space-x-8">
          {navItems.map((item) => (
            <a
              key={item.name}
              href={item.href}
              className="hover:text-green-200 transition-colors duration-200"
            >
              {item.name}
            </a>
          ))}
        </div>

        {/* Desktop Auth Button */}
        <div className="hidden md:block">
          {isSignedIn ? (
            <Button 
              onClick={onLogout}
              variant="outline" 
              className="text-green-600 border-white bg-white hover:bg-green-50"
            >
              Logout
            </Button>
          ) : (
            <Button 
              onClick={onLoginClick}
              variant="outline" 
              className="text-green-600 border-white bg-white hover:bg-green-50"
            >
              Login
            </Button>
          )}
        </div>

        {/* Mobile Menu Button */}
        <div className="md:hidden">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="text-white hover:bg-green-700"
          >
            {isMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </Button>
        </div>
      </div>

      {/* Mobile Navigation Menu */}
      {isMenuOpen && (
        <div className="md:hidden mt-4 pb-4 border-t border-green-500">
          <div className="flex flex-col space-y-3 pt-4">
            {navItems.map((item) => (
              <a
                key={item.name}
                href={item.href}
                className="hover:text-green-200 transition-colors duration-200 px-2 py-1"
                onClick={() => setIsMenuOpen(false)}
              >
                {item.name}
              </a>
            ))}
            <div className="pt-2">
              {isSignedIn ? (
                <Button 
                  onClick={onLogout}
                  variant="outline" 
                  className="text-green-600 border-white bg-white hover:bg-green-50 w-full"
                >
                  Logout
                </Button>
              ) : (
                <Button 
                  onClick={onLoginClick}
                  variant="outline" 
                  className="text-green-600 border-white bg-white hover:bg-green-50 w-full"
                >
                  Login
                </Button>
              )}
            </div>
          </div>
        </div>
      )}
    </nav>
  );
}
